// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccgraph.proto

package com.ccgraph.ccgraph;

/**
 * Protobuf type {@code CCGraphRPC.CallParam}
 */
public final class CallParam extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CCGraphRPC.CallParam)
    CallParamOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CallParam.newBuilder() to construct.
  private CallParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CallParam() {
    txnName_ = com.google.protobuf.ByteString.EMPTY;
    paramList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CallParam();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CallParam(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            txnName_ = input.readBytes();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              paramList_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000001;
            }
            paramList_.add(input.readBytes());
            break;
          }
          case 24: {

            retry_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        paramList_ = java.util.Collections.unmodifiableList(paramList_); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ccgraph.ccgraph.Ccgraph.internal_static_CCGraphRPC_CallParam_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ccgraph.ccgraph.Ccgraph.internal_static_CCGraphRPC_CallParam_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ccgraph.ccgraph.CallParam.class, com.ccgraph.ccgraph.CallParam.Builder.class);
  }

  public static final int TXN_NAME_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString txnName_;
  /**
   * <code>bytes txn_name = 1;</code>
   * @return The txnName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTxnName() {
    return txnName_;
  }

  public static final int PARAM_LIST_FIELD_NUMBER = 2;
  private java.util.List<com.google.protobuf.ByteString> paramList_;
  /**
   * <code>repeated bytes param_list = 2;</code>
   * @return A list containing the paramList.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getParamListList() {
    return paramList_;
  }
  /**
   * <code>repeated bytes param_list = 2;</code>
   * @return The count of paramList.
   */
  public int getParamListCount() {
    return paramList_.size();
  }
  /**
   * <code>repeated bytes param_list = 2;</code>
   * @param index The index of the element to return.
   * @return The paramList at the given index.
   */
  public com.google.protobuf.ByteString getParamList(int index) {
    return paramList_.get(index);
  }

  public static final int RETRY_FIELD_NUMBER = 3;
  private boolean retry_;
  /**
   * <code>bool retry = 3;</code>
   * @return The retry.
   */
  @java.lang.Override
  public boolean getRetry() {
    return retry_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!txnName_.isEmpty()) {
      output.writeBytes(1, txnName_);
    }
    for (int i = 0; i < paramList_.size(); i++) {
      output.writeBytes(2, paramList_.get(i));
    }
    if (retry_ != false) {
      output.writeBool(3, retry_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!txnName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, txnName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < paramList_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(paramList_.get(i));
      }
      size += dataSize;
      size += 1 * getParamListList().size();
    }
    if (retry_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, retry_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ccgraph.ccgraph.CallParam)) {
      return super.equals(obj);
    }
    com.ccgraph.ccgraph.CallParam other = (com.ccgraph.ccgraph.CallParam) obj;

    if (!getTxnName()
        .equals(other.getTxnName())) return false;
    if (!getParamListList()
        .equals(other.getParamListList())) return false;
    if (getRetry()
        != other.getRetry()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TXN_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getTxnName().hashCode();
    if (getParamListCount() > 0) {
      hash = (37 * hash) + PARAM_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getParamListList().hashCode();
    }
    hash = (37 * hash) + RETRY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRetry());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ccgraph.ccgraph.CallParam parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ccgraph.ccgraph.CallParam parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ccgraph.ccgraph.CallParam parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ccgraph.ccgraph.CallParam parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ccgraph.ccgraph.CallParam parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ccgraph.ccgraph.CallParam parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ccgraph.ccgraph.CallParam parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ccgraph.ccgraph.CallParam parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ccgraph.ccgraph.CallParam parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ccgraph.ccgraph.CallParam parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ccgraph.ccgraph.CallParam parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ccgraph.ccgraph.CallParam parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ccgraph.ccgraph.CallParam prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CCGraphRPC.CallParam}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CCGraphRPC.CallParam)
      com.ccgraph.ccgraph.CallParamOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ccgraph.ccgraph.Ccgraph.internal_static_CCGraphRPC_CallParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ccgraph.ccgraph.Ccgraph.internal_static_CCGraphRPC_CallParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ccgraph.ccgraph.CallParam.class, com.ccgraph.ccgraph.CallParam.Builder.class);
    }

    // Construct using com.ccgraph.ccgraph.CallParam.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      txnName_ = com.google.protobuf.ByteString.EMPTY;

      paramList_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      retry_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ccgraph.ccgraph.Ccgraph.internal_static_CCGraphRPC_CallParam_descriptor;
    }

    @java.lang.Override
    public com.ccgraph.ccgraph.CallParam getDefaultInstanceForType() {
      return com.ccgraph.ccgraph.CallParam.getDefaultInstance();
    }

    @java.lang.Override
    public com.ccgraph.ccgraph.CallParam build() {
      com.ccgraph.ccgraph.CallParam result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ccgraph.ccgraph.CallParam buildPartial() {
      com.ccgraph.ccgraph.CallParam result = new com.ccgraph.ccgraph.CallParam(this);
      int from_bitField0_ = bitField0_;
      result.txnName_ = txnName_;
      if (((bitField0_ & 0x00000001) != 0)) {
        paramList_ = java.util.Collections.unmodifiableList(paramList_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.paramList_ = paramList_;
      result.retry_ = retry_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ccgraph.ccgraph.CallParam) {
        return mergeFrom((com.ccgraph.ccgraph.CallParam)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ccgraph.ccgraph.CallParam other) {
      if (other == com.ccgraph.ccgraph.CallParam.getDefaultInstance()) return this;
      if (other.getTxnName() != com.google.protobuf.ByteString.EMPTY) {
        setTxnName(other.getTxnName());
      }
      if (!other.paramList_.isEmpty()) {
        if (paramList_.isEmpty()) {
          paramList_ = other.paramList_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureParamListIsMutable();
          paramList_.addAll(other.paramList_);
        }
        onChanged();
      }
      if (other.getRetry() != false) {
        setRetry(other.getRetry());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ccgraph.ccgraph.CallParam parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ccgraph.ccgraph.CallParam) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString txnName_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes txn_name = 1;</code>
     * @return The txnName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTxnName() {
      return txnName_;
    }
    /**
     * <code>bytes txn_name = 1;</code>
     * @param value The txnName to set.
     * @return This builder for chaining.
     */
    public Builder setTxnName(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      txnName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes txn_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTxnName() {
      
      txnName_ = getDefaultInstance().getTxnName();
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> paramList_ = java.util.Collections.emptyList();
    private void ensureParamListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        paramList_ = new java.util.ArrayList<com.google.protobuf.ByteString>(paramList_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated bytes param_list = 2;</code>
     * @return A list containing the paramList.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getParamListList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(paramList_) : paramList_;
    }
    /**
     * <code>repeated bytes param_list = 2;</code>
     * @return The count of paramList.
     */
    public int getParamListCount() {
      return paramList_.size();
    }
    /**
     * <code>repeated bytes param_list = 2;</code>
     * @param index The index of the element to return.
     * @return The paramList at the given index.
     */
    public com.google.protobuf.ByteString getParamList(int index) {
      return paramList_.get(index);
    }
    /**
     * <code>repeated bytes param_list = 2;</code>
     * @param index The index to set the value at.
     * @param value The paramList to set.
     * @return This builder for chaining.
     */
    public Builder setParamList(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureParamListIsMutable();
      paramList_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes param_list = 2;</code>
     * @param value The paramList to add.
     * @return This builder for chaining.
     */
    public Builder addParamList(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureParamListIsMutable();
      paramList_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes param_list = 2;</code>
     * @param values The paramList to add.
     * @return This builder for chaining.
     */
    public Builder addAllParamList(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureParamListIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, paramList_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes param_list = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearParamList() {
      paramList_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private boolean retry_ ;
    /**
     * <code>bool retry = 3;</code>
     * @return The retry.
     */
    @java.lang.Override
    public boolean getRetry() {
      return retry_;
    }
    /**
     * <code>bool retry = 3;</code>
     * @param value The retry to set.
     * @return This builder for chaining.
     */
    public Builder setRetry(boolean value) {
      
      retry_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool retry = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRetry() {
      
      retry_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CCGraphRPC.CallParam)
  }

  // @@protoc_insertion_point(class_scope:CCGraphRPC.CallParam)
  private static final com.ccgraph.ccgraph.CallParam DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ccgraph.ccgraph.CallParam();
  }

  public static com.ccgraph.ccgraph.CallParam getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CallParam>
      PARSER = new com.google.protobuf.AbstractParser<CallParam>() {
    @java.lang.Override
    public CallParam parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CallParam(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CallParam> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CallParam> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ccgraph.ccgraph.CallParam getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

