// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccgraph.proto

package com.ccgraph.ccgraph;

public interface CallParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CCGraphRPC.CallParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes txn_name = 1;</code>
   * @return The txnName.
   */
  com.google.protobuf.ByteString getTxnName();

  /**
   * <code>repeated bytes param_list = 2;</code>
   * @return A list containing the paramList.
   */
  java.util.List<com.google.protobuf.ByteString> getParamListList();
  /**
   * <code>repeated bytes param_list = 2;</code>
   * @return The count of paramList.
   */
  int getParamListCount();
  /**
   * <code>repeated bytes param_list = 2;</code>
   * @param index The index of the element to return.
   * @return The paramList at the given index.
   */
  com.google.protobuf.ByteString getParamList(int index);

  /**
   * <code>bool retry = 3;</code>
   * @return The retry.
   */
  boolean getRetry();
}
