// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccgraph.proto

package com.ccgraph.ccgraph;

public interface CommandParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CCGraphRPC.CommandParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes command = 1;</code>
   * @return The command.
   */
  com.google.protobuf.ByteString getCommand();
}
