// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccgraph.proto

package com.ccgraph.ccgraph;

public interface RetRowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CCGraphRPC.RetRow)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bytes one_row = 1;</code>
   * @return A list containing the oneRow.
   */
  java.util.List<com.google.protobuf.ByteString> getOneRowList();
  /**
   * <code>repeated bytes one_row = 1;</code>
   * @return The count of oneRow.
   */
  int getOneRowCount();
  /**
   * <code>repeated bytes one_row = 1;</code>
   * @param index The index of the element to return.
   * @return The oneRow at the given index.
   */
  com.google.protobuf.ByteString getOneRow(int index);
}
