// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccgraph.proto

package com.ccgraph.ccgraph;

/**
 * Protobuf type {@code CCGraphRPC.RetRow}
 */
public final class RetRow extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CCGraphRPC.RetRow)
    RetRowOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RetRow.newBuilder() to construct.
  private RetRow(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RetRow() {
    oneRow_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RetRow();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RetRow(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              oneRow_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000001;
            }
            oneRow_.add(input.readBytes());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        oneRow_ = java.util.Collections.unmodifiableList(oneRow_); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ccgraph.ccgraph.Ccgraph.internal_static_CCGraphRPC_RetRow_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ccgraph.ccgraph.Ccgraph.internal_static_CCGraphRPC_RetRow_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ccgraph.ccgraph.RetRow.class, com.ccgraph.ccgraph.RetRow.Builder.class);
  }

  public static final int ONE_ROW_FIELD_NUMBER = 1;
  private java.util.List<com.google.protobuf.ByteString> oneRow_;
  /**
   * <code>repeated bytes one_row = 1;</code>
   * @return A list containing the oneRow.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getOneRowList() {
    return oneRow_;
  }
  /**
   * <code>repeated bytes one_row = 1;</code>
   * @return The count of oneRow.
   */
  public int getOneRowCount() {
    return oneRow_.size();
  }
  /**
   * <code>repeated bytes one_row = 1;</code>
   * @param index The index of the element to return.
   * @return The oneRow at the given index.
   */
  public com.google.protobuf.ByteString getOneRow(int index) {
    return oneRow_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < oneRow_.size(); i++) {
      output.writeBytes(1, oneRow_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < oneRow_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(oneRow_.get(i));
      }
      size += dataSize;
      size += 1 * getOneRowList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ccgraph.ccgraph.RetRow)) {
      return super.equals(obj);
    }
    com.ccgraph.ccgraph.RetRow other = (com.ccgraph.ccgraph.RetRow) obj;

    if (!getOneRowList()
        .equals(other.getOneRowList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOneRowCount() > 0) {
      hash = (37 * hash) + ONE_ROW_FIELD_NUMBER;
      hash = (53 * hash) + getOneRowList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ccgraph.ccgraph.RetRow parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ccgraph.ccgraph.RetRow parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ccgraph.ccgraph.RetRow parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ccgraph.ccgraph.RetRow parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ccgraph.ccgraph.RetRow parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ccgraph.ccgraph.RetRow parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ccgraph.ccgraph.RetRow parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ccgraph.ccgraph.RetRow parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ccgraph.ccgraph.RetRow parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ccgraph.ccgraph.RetRow parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ccgraph.ccgraph.RetRow parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ccgraph.ccgraph.RetRow parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ccgraph.ccgraph.RetRow prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CCGraphRPC.RetRow}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CCGraphRPC.RetRow)
      com.ccgraph.ccgraph.RetRowOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ccgraph.ccgraph.Ccgraph.internal_static_CCGraphRPC_RetRow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ccgraph.ccgraph.Ccgraph.internal_static_CCGraphRPC_RetRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ccgraph.ccgraph.RetRow.class, com.ccgraph.ccgraph.RetRow.Builder.class);
    }

    // Construct using com.ccgraph.ccgraph.RetRow.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      oneRow_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ccgraph.ccgraph.Ccgraph.internal_static_CCGraphRPC_RetRow_descriptor;
    }

    @java.lang.Override
    public com.ccgraph.ccgraph.RetRow getDefaultInstanceForType() {
      return com.ccgraph.ccgraph.RetRow.getDefaultInstance();
    }

    @java.lang.Override
    public com.ccgraph.ccgraph.RetRow build() {
      com.ccgraph.ccgraph.RetRow result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ccgraph.ccgraph.RetRow buildPartial() {
      com.ccgraph.ccgraph.RetRow result = new com.ccgraph.ccgraph.RetRow(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        oneRow_ = java.util.Collections.unmodifiableList(oneRow_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.oneRow_ = oneRow_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ccgraph.ccgraph.RetRow) {
        return mergeFrom((com.ccgraph.ccgraph.RetRow)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ccgraph.ccgraph.RetRow other) {
      if (other == com.ccgraph.ccgraph.RetRow.getDefaultInstance()) return this;
      if (!other.oneRow_.isEmpty()) {
        if (oneRow_.isEmpty()) {
          oneRow_ = other.oneRow_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureOneRowIsMutable();
          oneRow_.addAll(other.oneRow_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ccgraph.ccgraph.RetRow parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ccgraph.ccgraph.RetRow) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.protobuf.ByteString> oneRow_ = java.util.Collections.emptyList();
    private void ensureOneRowIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        oneRow_ = new java.util.ArrayList<com.google.protobuf.ByteString>(oneRow_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated bytes one_row = 1;</code>
     * @return A list containing the oneRow.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getOneRowList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(oneRow_) : oneRow_;
    }
    /**
     * <code>repeated bytes one_row = 1;</code>
     * @return The count of oneRow.
     */
    public int getOneRowCount() {
      return oneRow_.size();
    }
    /**
     * <code>repeated bytes one_row = 1;</code>
     * @param index The index of the element to return.
     * @return The oneRow at the given index.
     */
    public com.google.protobuf.ByteString getOneRow(int index) {
      return oneRow_.get(index);
    }
    /**
     * <code>repeated bytes one_row = 1;</code>
     * @param index The index to set the value at.
     * @param value The oneRow to set.
     * @return This builder for chaining.
     */
    public Builder setOneRow(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOneRowIsMutable();
      oneRow_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes one_row = 1;</code>
     * @param value The oneRow to add.
     * @return This builder for chaining.
     */
    public Builder addOneRow(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOneRowIsMutable();
      oneRow_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes one_row = 1;</code>
     * @param values The oneRow to add.
     * @return This builder for chaining.
     */
    public Builder addAllOneRow(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureOneRowIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, oneRow_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes one_row = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOneRow() {
      oneRow_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CCGraphRPC.RetRow)
  }

  // @@protoc_insertion_point(class_scope:CCGraphRPC.RetRow)
  private static final com.ccgraph.ccgraph.RetRow DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ccgraph.ccgraph.RetRow();
  }

  public static com.ccgraph.ccgraph.RetRow getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RetRow>
      PARSER = new com.google.protobuf.AbstractParser<RetRow>() {
    @java.lang.Override
    public RetRow parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RetRow(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RetRow> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RetRow> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ccgraph.ccgraph.RetRow getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

