// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ccgraph.proto

package com.ccgraph.ccgraph;

public interface StartParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CCGraphRPC.StartParam)
    com.google.protobuf.MessageOrBuilder {
}
